server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunguoonline?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: yunguoOnline
  redis:
    host: 127.0.0.1
    port: 6379
    database: 3
    password:
  mail:
    # 指定邮件服务器地址
    host: smtp.qq.com
    # 登录账户
    username: 1115406904@qq.com
    # 登录密码
    password: "ofsbmrrjytnjfdic"
    # 端口
    port: 465
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
# 微信小程序支付配置信息
#wx:
#  # 微信小程序appid
#  app-id: wx252d685c1ac33339
#  # 商户号
#  mch-id: xxxx
#  # 证书序列号
#  mch-serial-no: xxxxx
#  # 小程序密钥
#  app-secret: e41dd65195e62e0f57a8be2fac146d12
#  # api密钥
#  api-key: xxxxxxxx
#  # 回调接口地址
#  notify-url: https://xxxx/a/biz/wxpay/payNotify
#  # 证书地址
#  key-path: yunguoOnline/src/main/resources/cert/apiclient_key.pem
custom:
  scheduled:
    cron: 0/10 * * * * ?
    fixedRate: 5000
    fixedDelay: 10000
    initialDelay: 1000
auth:
  token: hz123456uio
#  z4SGsCY0rsk0On0cGAyUjMI5nA0agT6t
#upload:
#  directory: G:\\图

